### ISSUE TITLE
The Disk Controller Type cannot be modified inside compute profiles

### ISSUE THREAD

**Issue by hlawatschek** [tristanrobert/foreman_fog_proxmox#53]
**Describe the bug**
When I try to modify the disk controller type in the compute resource it always falls back to scsi.

**To Reproduce**
1. Go to compute resource
2. change the disk controller type to VirtIO
3. Click on "Submit"
4. the disk controller type falls back to scsi.

**Expected behavior**
The disk controller type is changed to VirtIO

**Comment by tristanrobert** [comment]
I can't reproduce the bug. I think it is already fixed in 0.5.5 with #47

**Comment by hlawatschek** [comment]
This still happens in the compute profile section. 
Infrastructure -> Compute Profiles -> 1-Small -> <Proxmox Compute Ressource>

**Comment by hlawatschek** [comment]
Hi Tristan, 
have you tried to modify the disk controller inside the compute profile?
Infrastructure -> Compute Profiles -> 1-Small ->
I fear it still does not work here.

**Comment by quba42** [comment]
@tristanrobert, @hlawatschek, I can confirm that compute profiles keep falling back to Controller "SCSI" if I try to change it to anything else.

**Comment by hlawatschek** [comment]
hi @tristanrobert would you mind to verify this report again?
Does "modifying the disk controller to "VirtIO" inside the compute profile" really work for you?
Infrastructure -> Compute Profiles -> 1-Small ->
